### ISSUE TITLE
MVP for `kn quickstart` 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/ux#43]
See https://github.com/knative-sandbox/kn-plugin-quickstart for plugin Directory 

MVP Scope: 

`User Installs Plugin` 
```
As Nelly the New User 
I want to easily install the plugin via homebrew or binary 
So that I can install this developer tool the same I way I am used to installing other dev tools 
```

`User runs: kn quickstart --kind`
```
As Nelly the New User 
I want to install the Knative Quickstart environment on Kind (scripts found in konk.dev)
So that I can easily get started with Knative
And so that I don't have to curl to bash 
```

**Comment by csantanapr** [comment]
I think we should not do `kn quickstart --minikube` as MVP

Thomas Strömberg minikube contributor suggested a minikube addon knative  `minikube start --addons knative` 
https://twitter.com/thomrstrom/status/1401314503686381571?s=20

Having `minikube start --addons knative` might be a better user experience than `kn quickstart --minikube` since the `tunnel` part can be worked out better in minikube

**Comment by omerbensaadon** [comment]
Agreed, removed

**Comment by csantanapr** [comment]
I was thinking on having a `--docker-desktop`  which user might already have install. but docker desktop is not available for Linux developers so doing `--kind` makes sense.

We can see what makes sense to implement after MVP `--kind` which should cover all users Windows, Linux and MacOS

**Comment by csantanapr** [comment]
Also if someone wants to start work in parallel on `minikube start --addons knative`  on the minikube code base that could also be a community-supported option.

**Comment by csantanapr** [comment]
MVP is done and kn quickstart for kind shipped 🎉
